.travis.yml
packtivity/handlers/execution_handlers.py
packtivity/logutils.py
packtivity/syncbackends.py

* make setup_logging a context and remove handlers on ctx exit
with scaling tests with >1k nodes we ran into crash due to
"too many open files"

logging: clean up opened filehandles (scaling)

---

packtivity/logutils.py

* the handlers were setup correctly, but the overall logger level
needs to be set to DEBUG such that debug messages are even send
to the appropriate loggers

logging: setLevel on logger to capture debug messgaes

---

packtivity/backendutils.py
packtivity/statecontexts/__init__.py
packtivity/statecontexts/posixfs_context.py

* load state provider from env if fromenv, plugins need to define load_provider
* type check readwrite / readonly lists (common mistake to give just str of single path)
* generic load_proxy function for async proxies

state & proxy: various fixes

---

packtivity/asyncbackends.py

this is necessary if you are running multiple independent celery instances
(such as in yadage service cluster)

celery backend: add switch to tweak disable sync in result.get()

---

packtivity/handlers/execution_handlers.py

* only check PACKTIVITY_DRYRUN in actual execution code, not in argv prep

fix dryrun

---

.github/workflows/ci.yml
.github/workflows/publish-package.yml
LICENSE
MANIFEST.in
setup.py

```
* Add MIT License
* Add MANIFEST.in
* Add python_requires to setup.py to require Python 2.7 or Python 3.6+
* Add PyPI metadata classifiers to setup.py
* Add workflow dispatch to CI
* Update publishing workflow to use the build package to build an sdist
and a wheel
* Publish to TestPyPI on tags and publish to PyPI on GitHub releases
```

ci: Update publishing workflow to use build and run on releases

---

packtivity/handlers/execution_handlers.py

Resolves #77 
Running
```console
pydoc subprocess.Popen
```
shows
```
subprocess.Popen(args, bufsize=-1, ...
```
As "line buffering (buffering=1) isn't supported in binary mode", then remove the line buffering by removing the `bufsize` and letting it default to `-1`.
c.f. https://docs.python.org/3/library/subprocess.html#subprocess.Popen especially
> bufsize will be supplied as the corresponding argument to the [`open()`](https://docs.python.org/3/library/functions.html#open) function when creating the stdin/stdout/stderr pipe file objects:
> 
> * 0 means unbuffered (read and write are one system call and can return short)
> * 1 means line buffered (only usable if `universal_newlines=True` i.e., in a text mode)
> * any other positive value means use a buffer of approximately that size
> * …

fix: Remove bufsize argument from subprocess.Popen

---

.github/workflows/publish-package.yml

```
* Add GitHub release publication events to triggers for package
publishing workflow.
- This is a fix that will enable deploying to PyPI through creation
of GitHub releases.
- Amends PR #79
```

ci: Enable deployment to PyPI on GitHub release

---

.github/workflows/ci.yml
.github/workflows/publish-docker.yml
.github/workflows/publish-package.yml

```
* Update GitHub Actions to latest releases.
* Remove deprecated Pythons (3.6) from testing matrix.
* Update Docker build workflows.
```

ci: Remove deprecated Pythons from CI

---

Dockerfile

centos:8 is now dead, so use almalinux:9.1 as CERN is adopting AlmaLinux

fix: Update Dockerfile base to almalinux:9.1

---

setup.py

Resolves #89
* Fix requires a new release of kombu
- c.f. https://github.com/celery/celery/issues/7783#issuecomment-1283638046
* This should be viewed as temporary. As soon as there is a new release of kombu the release with this fix in in should get yanked in favor of a new release without this restriction.
* Add lower bound of celery>=5.0.0.
```
* Fix requires a new release of kombu
- c.f. https://github.com/celery/celery/issues/7783#issuecomment-1283638046
- This should be viewed as temporary. As soon as there is a new release of kombu
the release with this fix in in should get yanked in favor of a new release
without this restriction.
* Add lower bound of celery>=5.0.0.
```

fix: Add importlib-metadata constraint to avoid celery import bug

---

.github/workflows/ci.yml
setup.py

Resolves #91
* Python 3.7 is EOL on 2023-06-27 so only support Pythons with support from the PSF.
```
$ eol python
┌───────┬────────────┬─────────┬────────────────┬────────────┐
│ cycle │  release   │ latest  │ latest release │    eol     │
├───────┼────────────┼─────────┼────────────────┼────────────┤
│ 3.11  │ 2022-10-24 │ 3.11.4  │   2023-06-06   │ 2027-10-24 │
│ 3.10  │ 2021-10-04 │ 3.10.12 │   2023-06-06   │ 2026-10-04 │
│ 3.9   │ 2020-10-05 │ 3.9.17  │   2023-06-06   │ 2025-10-05 │
│ 3.8   │ 2019-10-14 │ 3.8.17  │   2023-06-06   │ 2024-10-14 │
│ 3.7   │ 2018-06-26 │ 3.7.17  │   2023-06-05   │ 2023-06-27 │
│ 3.6   │ 2016-12-22 │ 3.6.15  │   2021-09-03   │ 2021-12-23 │
│ 3.5   │ 2015-09-12 │ 3.5.10  │   2020-09-05   │ 2020-09-13 │
│ 3.4   │ 2014-03-15 │ 3.4.10  │   2019-03-18   │ …
```

build: Require Python 3.8+

---

setup.py

In relation to Issue #96 
Place an upper limit on jq of '<1.6.0' as jq (the Python library) v1.6.x+ are compatible with jq (the language) v1.7+ and packtivity is currently compatible with jq (the language) v1.6.
- This should be viewed as a temporary stopgap measure to avoid large yadage ecosystem breakage and should be reverted as soon as a workaround is found.
```
* Place an upper limit on jq of '<1.6.0' as jq (the Python library)
v1.6.x+ are compatible with jq (the language) v1.7+ and packtivity
is currently compatible with jq (the language) v1.6.
- This should be viewed as a temporary stopgap measure to avoid large
yadage ecosystem breakage and should be reverted as soon as a
workaround is found.
- c.f. https://github.com/yadage/packtivity/issues/96
```

build: Restrict jq to jqlang pre v1.7

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/publish-docker.yml
.github/workflows/publish-package.yml

* Update GitHub Action workflows:
- actions/checkout: v3 -> v4
- pypa/gh-action-pypi-publish: v1.6.4 -> v1.8.10
- docker/setup-qemu-action: v2 -> v3
- docker/setup-buildx-action: v2 -> v3
- docker/login-action: v2 -> v3
- docker/build-push-action: v4 -> v5
* Add dependabot updater for GitHub Actions

ci: Update GitHub Action workflows

---

packtivity/datamodels/purejson.py
packtivity/typedleafs.py
packtivity/utils.py
setup.py

Part of Issue #96 
The 'leaf_paths' filter has been deprecated for 9 years and was removed in jqlang v1.7 (jq v1.6) so use the 'paths(scalars)' filter.
- c.f. https://github.com/jqlang/jq/pull/2666
- c.f. https://github.com/jqlang/jq/pull/426
```
* The 'leaf_paths' filter has been deprecated for 9 years and was
removed in jqlang v1.7 (jq v1.6) so use the 'paths(scalars)' filter.
- c.f. https://github.com/jqlang/jq/pull/2666
- c.f. https://github.com/jqlang/jq/pull/426
* Remove upper bound on jq version
- Reverts https://github.com/yadage/packtivity/pull/97
```

fix: Use 'paths(scalars)' as 'leaf_paths' filter is deprecated 

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/publish-docker.yml
.github/workflows/publish-package.yml

```
* Backport PR https://github.com/yadage/packtivity/pull/98
```

ci(backport): Update GitHub Actions

---

packtivity/datamodels/purejson.py
packtivity/typedleafs.py
packtivity/utils.py
setup.py

* The 'leaf_paths' filter has been deprecated for 9 years and was removed in jqlang v1.7 (jq v1.6) so use the 'paths(scalars)' filter.
- c.f. https://github.com/jqlang/jq/pull/2666
- c.f. https://github.com/jqlang/jq/pull/426
* Remove upper bound on jq version
- Reverts https://github.com/yadage/packtivity/pull/97
* Backport PR #99 
```
* Backport PR https://github.com/yadage/packtivity/pull/99
* The 'leaf_paths' filter has been deprecated for 9 years and was removed in jqlang v1.7 (jq v1.6) so use the 'paths(scalars)' filter.
- c.f. https://github.com/jqlang/jq/pull/2666
- c.f. https://github.com/jqlang/jq/pull/426
* Remove upper bound on jq version
- Reverts https://github.com/yadage/packtivity/pull/97
```

fix(backport): Use 'paths(scalars)' as 'leaf_paths' filter is deprecated

---

packtivity/statecontexts/posixfs_context.py
setup.py

Resolves #109.
* Use dirhash library over checksumdir, as dirhash is maintained and checksumdir is not.
- c.f. https://github.com/to-mc/checksumdir
- state_hash states it returns the SHA1 hash, so use sha1 for the algorithm.
* Apply isort.

build: Use dirhash dependency for dir hashes

---

.github/workflows/ci.yml
setup.py

* Add Python 3.12 to the CI testing matrix.
* Default to Python 3.12 in CI workflows.
* Add Python 3.12 to metadata.

ci: Add Python 3.12 to testing

---

README.md

* Update tools to point to https://github.com/yadage/ GitHub org.
* Update packtivity example to commit level for long term access.

docs: Update README URLs to current locations

---

.bumpversion.cfg
CITATION.cff
setup.py

* Add Citation File Format file to repo to get repository cite button on GitHub.
- c.f. https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files
* Add CITATION.cff to bump2version control.
* Add Matthew Feickert to authors.

docs: Add CITATION.cff Citation File Format file

---

packtivity/statecontexts/posixfs_context.py

style: Apply black formatting
